### ISSUE TITLE
Guardian search inaccurate

### ISSUE THREAD

**Issue by moahmed0987** [tobynott80/find-my-mp-web#2]
When loading news results for an MP, the search is finding all results for each word in the name.
E.g., For Jo Stevens, results for "Jo" come up and results for "Stevens" come up. Instead results for "Jo Stevens" should come up. 
This can be fixed by adding an "AND" between the two names (https://open-platform.theguardian.com/documentation/).
This would look like this: https://content.guardianapis.com/search?q=Jo AND Stevens

**Comment by tobynott80** [comment]
Thanks for picking this up Mo! I'll get started on the fix.
