### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by moahmed0987** [tobynott80/find-my-mp-web#6]
The current documentation inaccurately describes the purpose of the website as "A website to gather information on a local MP (UK&NI)". It is important to note that the long form name of the United Kingdom is "The United Kingdom of Great Britain and Northern Ireland", which includes Northern Ireland. Thus, a more accurate description would be either "A website to gather information on a local MP (UK)" or "A website to gather information on a local MP (GB&NI)".

**Comment by tobynott80** [comment]
Great spot Mo! I had no idea - will make the change now 😀
